import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image';
import Logo from '../../imgs/logo.png';


export default function Header() {
  
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        
        </Head>

  <header>


  <nav className="navbar navbar-expand-lg navbar-light bg-light">
            <div className="container-fluid">
              <a className="navbar-brand flex-fill" href="../">
              <div className="logo">
                <Image
                    src={Logo}
                    alt="Villa SULT logo"
                    width={391}
                    height={41}
                    blurDataURL="data:..." 
                    placeholder="blur" 
                />
      </div>
              </a>
              <button className="navbar-toggler flex-fill" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <p>Meny</p>
              </button>
              <div className="collapse navbar-collapse flex-fill" id="navbarSupportedContent">
                <ul className="nav nav-tabs flex-fill" id="myTab" role="tablist">
                    <li className="nav-item flex-fill" role="presentation">
                      <button className="nav-link tab" id="courses-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="kurs" aria-selected="false"><Link href="/allCourses"><a>Kurs og utdannelser</a></Link></button>
                    </li>
                    <li className="nav-item flex-fill" role="presentation">
                      <button className="nav-link tab" id="om-tab" data-bs-toggle="tab" data-bs-target="#news" type="button" role="tab" aria-controls="om" aria-selected="false"><Link href="/omOss"><a>Om oss</a></Link></button>
                    </li>
                    <li className="nav-item flex-fill " role="presentation">
                      <button className="nav-link tab" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="kontakt" aria-selected="false"><Link href="/kontaktOss"><a>Kontakt oss</a></Link></button>
                    </li>
                    <li className="nav-item flex-fill" role="presentation">
                      <button className="nav-link tab admin" id="admin-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="admin" aria-selected="false"> <Link href="/adminLogin"><a>Admin</a></Link></button>
                    </li>
                    
                  </ul>   
                 </div>
                
            </div>
          </nav>
      
  </header>
      </div>
    );
  }