import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";

import Header from "../../components/header";
import Footer from '../../components/footer';

export default function Upcoming() {
  const router = useRouter();
  const [courses, setCourses] = useState([]);

  const handleOnClick = (id) => {
    router.push(`/details/${id}`);
  };

  useEffect(() => {
    const getCourses = async () => {
        const response = await fetch('http://localhost:1337/api/courses/');
        const data = await response.json();
        const result = data.data;
       console.log(result);
        setCourses(result);
      
    };

    getCourses();
  }, []);

  console.log("courses", courses);

  return (
    <div className={styles.container}>
      <Head>
        <title>Dynamic routes example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main className="all-courses_main">
        <div className="all-courses_list">
          <ul>
            {courses.map((course) => (
                <div className="upcoming_card"> 
                <div class="short-title_box"><h3>{course.attributes.short_title}</h3></div>
                <div class="date_box"><h4>{course.attributes.kurs_date}</h4></div>
              <li key={course.id} onClick={() => handleOnClick(course.id)}>
              <div class="details_btn">
        <a>Les mer/Påmelding</a>
        </div>
              </li>
              </div>
            ))}
          </ul>
        </div>
      </main>


    </div>
  );
}