import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Header from "../../components/header";
import Footer from "../../components/footer";

export default function Course({ kurs_id, kurs_description, kurs_info, kurs_start_title, kurs_start, kurs_content_title, kurs_content, kurs_arbeidsform_title, kurs_arbeidsform, kurs_target_audience_title, kurs_target_audience}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>People</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Header></Header>
      <main className="details_main">
      <div className="om-oss_container">
        <h1>{kurs_id}</h1>
          <h2>{kurs_description}</h2>
          <h3>{kurs_info}</h3>
          <h4>{kurs_start_title}</h4>
          <h5>{kurs_start}</h5>
          <h4>{kurs_content_title}</h4>
          <h5>{kurs_content}</h5>

          <h4>{kurs_arbeidsform_title}</h4>
          <h5>{kurs_arbeidsform}</h5>
          <h4>{kurs_target_audience_title}</h4>
          <h5>{kurs_target_audience}</h5>
        </div>
      </main>

     <Footer></Footer>
    </div>
  );
}

export async function getStaticPaths() {
  // Return a list of possible value for id

  const getCourses = async () => {
    const response = await fetch('http://localhost:1337/api/courses/');
    const data = await response.json();
    const result = data.data;
    console.log(result);
    return result;
  };

  const allCourses = await getCourses();

  const paths = allCourses.map((course) => {
    return {
      params: {
        id: course.id.toString(),
      },
    };
  });

  // paths = [
  //   {
  //     params: {
  //       guid: "86a8a038-11df-4315-9d20-1d9f299a1007",
  //     },
  //   },
  //   {
  //     params: {
  //       guid: "86a8a038-11df-4315-9d20-123123312",
  //     },
  //   },
  // ];

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  // Fetch necessary data for the blog post using params.id
  // const foundPerson = peopleJson.find((person) => person.guid === params.guid);

  // We need to fetch the data for one spefici character here
  const fetchCourse = async () => {
    const response = await fetch(
      `http://localhost:1337/api/courses/${params.id}`
    );
    const data = await response.json();
    const result = data.data;
    console.log(result.attributes , "hello")
    return result.attributes;
  };
  const foundCourse = await fetchCourse();

  return {
    props: foundCourse,
  };
}

// import Head from "next/head";
// import Image from "next/image";
// import styles from "../../styles/Home.module.css";


// export default function Courses({ kurs_id, kurs_description, kurs_info }) {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Kurs</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>{kurs_id}</h1>

//         <div>
//           <p>{kurs_description}</p>
//           <p>{kurs_info}</p>
//         </div>
//       </main>

      
//     </div>
//   );
// }

// export async function getStaticPaths() {
  // Return a list of possible value for id

  // const getCharacters = async () => {
  //   const response = await fetch("http://localhost:1337/api/courses");
  //   const data = await response.json();
  //   const results = data.data; 
  //   return results.data;
  // };

  // const allCharacters = await getCharacters();

  // const paths = allCharacters.map((course) => {
  //   return {
  //     params: {
  //       id: course.id.toString(),
  //     },
  //   };
  // });

  // paths = [
  //   {
  //     params: {
  //       guid: "86a8a038-11df-4315-9d20-1d9f299a1007",
  //     },
  //   },
  //   {
  //     params: {
  //       guid: "86a8a038-11df-4315-9d20-123123312",
  //     },
  //   },
  // ];

//   return {
//     paths,
//     fallback: false,
//   };
// }

// export async function getStaticProps({ params }) {
//   // Fetch necessary data for the blog post using params.id
//   // const foundPerson = peopleJson.find((person) => person.guid === params.guid);

//   // We need to fetch the data for one spefici character here
//   const fetchCharacter = async () => {
//     const data = await fetch(
//       `http://localhost:1337/api/courses/${params.id}`
//     );
//     const json = await data.json();
//     return json;
//   };
//   const foundPerson = await fetchCharacter();

//   return {
//     props: foundPerson,
//   };
// }

// export default function Course({kurs_id, kurs_description, kurs_info}) {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>People</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>{kurs_id}</h1>

//         <div>
//           <p>{kurs_description}</p>
//           <p>{kurs_info}</p>
//         </div>
//       </main>

     
//     </div>
//   );
// } 

// export const getStaticPaths = async () => {
//   const coursesArray = await fetch("http://localhost:1337/api/courses");

//   const paths = coursesArray.map((courses) => {
//     return {
//       params: { id: courses.id.toString() },
//     };
//   });

//   return {
//     paths,
//     fallback: false,
//   };
// };

// export const getStaticProps = async (context) => {
//   const id = context.params.id;
//   const courses = await fetch("http://localhost:1337/api/courses" + '/' + id);
//   return {
//     props: { courses: courses },
    
//   };
// };


// function CoursesDetail (
//   {courses: {
//     id,
//     kurs_id,
//     kurs_description,
//     kurs_info,
//     kurs_start_title,
//     kurs_start,
//     kurs_content_title,
//     kurs_content,
//     kurs_arbeidsform_title,
//     kurs_arbeidsform,
//     kurs_tema_title,
//     kurs_tid_sted_title,
//     kurs_tid_sted,
//     kurs_registration_title,
//     kurs_registration,
//     kurs_target_audience,
//     kurs_target_audience_filter,
//     }
//   }
// ){};


