import Head from "next/head";
import Header from "../../components/header";
import Footer from "../../components/footer";
import styles from "../../styles/Home.module.css";
import Course from "../details/[id]";

export default function Home() {
  const router = useRouter();
  const [courses, setCourses] = useState([]);

  const handleOnClick = (id) => {
    router.push(`/details/${id}`);
  };

  useEffect(() => {
    const getCourses = async () => {
        const response = await fetch('http://localhost:1337/api/courses/');
        const data = await response.json();
        const result = data.data;
       console.log(result);
        setCourses(result);
      
    };

    getCourses();
  }, []);

  console.log("courses", courses);
  return (
    <div className={styles.container}>
      <Head>
        <title>Kurs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<Header></Header>
      <main className={styles.main}>
        <h1 className={styles.title}>Kurs</h1>

        <div>
         
          {/* <ul>
            {peopleJson.map((course) => (
              <li key={person.guid}>{person.name}</li>
            ))}
          </ul> */}
        </div>
      </main>

     <Footer></Footer>
    </div>
  );
}

// import Head from "next/head";

// import styles from "../../styles/Home.module.css";


// export default function Home() {
//   const router = useRouter();
//   const [courses, setCourses] = useState([]);

//   const handleOnClick = (id) => {
//     router.push(`/courses/${id}`);
//   };

//   useEffect(() => {
//     const getCourses = async () => {
//         const response = await fetch('http://localhost:1337/api/courses/');
//         const data = await response.json();
//         const result = data.data;
//        console.log(result , "hello");
//         setCourses(result);
      
//     };

//     getCourses();
//   }, []);

//   console.log("courses", courses);
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Kurs</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>People</h1>

//         <div>
//           {/* <ul>
//             {peopleJson.map((person) => (
//               <li key={person.guid}>{person.name}</li>
//             ))}
//           </ul> */}
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <p>Made with ❤</p>
//       </footer>
//     </div>
//   );
// }


// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../../styles/Home.module.css'
// import Header from '../../components/header'
// import Script from 'next/script'
// import { GetMeDetails } from '../../components/details'
// import Footer from '../../components/footer'
// import Link from 'next/link'
// import Course from '../details/[id]'
// import allCourses from '../details/[id]'
// import { useRouter } from "next/router";
// import { useState, useEffect } from "react";
// import allCharacters from '../details/[id]';

// export default function Home() {
//   const router = useRouter();
//   const [courses, setCourses] = useState([]);

//   const handleOnClick = (id) => {
//     router.push(`/${id}`);
//   };

//   useEffect(() => {
//     const getCourses = async () => {
//       const response = await fetch("http://localhost:1337/api/courses");
//       const data = await response.json();
//       const results = data.data;
//       setCourses(results.json);
//     };

//     getCourses();
//   }, []);

//   console.log("courses", courses);
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>People</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <Header></Header>
      
//       <main className={styles.main}>
//         <h1 className={styles.title}>Course</h1>

//         <div>
         
//         </div>
//       </main>

//      <Footer></Footer>
//      <div className="container">
// <Script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></Script>
// <Script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></Script>
// <Script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></Script>
//       </div>
//     </div>
//   );
// }

// export default function details() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <Header></Header>
      
//       <main className={styles.main}>
     
//       <Course></Course>
      
//       {/* <div className="details">
//       {Course((course) => (
//               <li key={course.guid}>{course.kurs_id}</li>
//             ))}
//       </div> */}
     
       
//       </main>
      
//       <Footer></Footer>
     
//       <div className="container">
// <Script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></Script>
// <Script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></Script>
// <Script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></Script>
//       </div>
//     </div>
//   )
// }

