import Head from 'next/head'
import Link from 'next/link';
// import Image from 'next/image';
// import Villasult from '../../imgs/villasult.png';
// import Spiseforstyrrelse from '../../imgs/spiseforstyrrelse.png'
import styles from "../../styles/Home.module.css";



export default function OmOss() {
  
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        
        </Head>

            <main className="om-oss_main">
            <div className="om-oss_container">
                <h1>Om oss</h1>
                <h2>Stiftelsen Institutt for spiseforstyrrelser ble etablert som ideell stiftelse av Pål Georg Gundersen og Finn Skårderud i 2014.</h2>
                <h4>Organisasjonen er en videreføring av psykiater Finn Skårderuds foretak Institutt for spiseforstyrrelser, etablert i 1997. Instituttet er en rammeorganisasjon for flere virksomheter: behandling, forskning, undervisning og utdannelse. Utover dette har stiftelsen en eksplisitt ambisjon om å være i dialog med miljøer for kunst og kulturformidling. Stiftelsen skal også å være en del av den offentlige debatten om spiseforstyrrelser og beslektete temaer.</h4>
                <h3>Styret:</h3>
                <h4>Stiftelsens styre består av styreleder Fabian Stang og styremedlemmene Pål Georg Gundersen, Hege Bømark, Kristin Lien Selvaag, Linnea Myhre og Magne Furuholmen.</h4>
                <h3>Huset:</h3>
                <h4>Villa SULT i Kruses gate 8 på Frogner i Oslo het opprinnelig Villa Hurum. Den er unik i estetisk forstand – bygd i den arkitektoniske tradisjonen art noveau, på tysk kalt Jugendstil. Villaen har en sydvendt hovedfasade med Oslos mest bemerkelsesverdige art nouveau-detaljer. Utformingen ligner på Observatorie-gaten 2b, og begge husene er gitt form av arkitekten Alf Hurum. Kruses gate 8 ble bygget i 1899 for arkitektens bror, Arthur Hurum, som drev slipsfabrikken Hurum & Co. I 1908 ble Villa Hurum kjøpt av Bogstad gårds eier Westye Egeberg og anvendt som byresidens. Et hus preget av omtanke i estetikk og design gir godt grunnlag for omtanke og omsorg i de aktivitetene som skal prege huset.</h4>

            </div>
            </main>
      </div>
    );
  }