import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image';
import Villasult from '../../imgs/villasult.png';
import Spiseforstyrrelse from '../../imgs/spiseforstyrrelse.png'


export default function Boxes() {
  
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        
        </Head>

            <main>
                <div className="boxes">
                <div className="box_one">
                <Link href="https://spiseforstyrrelser.no/activities/vi-skreddersyr-kurs-utdannelse-og-veiledning-til-avdelinger-og-institusjoner/"><a className="faglig_veiledning">Faglig veiledning</a></Link>    
                </div>
                <div className="box_one">
                <Link href="/allCourses"><a className="utdannelser">Utdannelser</a></Link>
                </div>
                <div className="box_one">
               <Link href="/allCourses"><a className="kurs_seminarer">Kurs Seminarer</a></Link>
                </div>
                </div>
                <div className="boxes">
                <div className="box_two">
                    <div className="film-container">
                    <iframe width="100%" height="100%" src="https://www.youtube.com/embed/vEzn1Hwiiuw" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
                    </div>
            
                </div>
                
                <div className="box_two">
                    <div className={'image-container'}>
                    <Image
                        src={Villasult}
                        alt="Villa SULT bygning"
                        layout="fill"
                        className={'image'}
                        // width={240}
                        // height={180}
                        blurDataURL="data:..." 
                        placeholder="blur" 
                    />
                    </div>
                    <Link href="/omOss"><a>Om oss</a></Link>
                </div>
                <div className="box_two">
                    <div className={'image-container'}>
                        <Image
                            src={Spiseforstyrrelse}
                            alt="Jeg har en spiseforstyrrelse"
                            layout="fill"
                            className={'image'}
                            // width={240}
                            // height={180}
                            blurDataURL="data:..." 
                            placeholder="blur" 
                        />
                        </div>
                        <Link href="#"><a className="spiseforstyrrelse">Jeg har en spiseforstyrrelse</a></Link>
                       
                </div>
                </div>
            </main>
      </div>
    );
  }