import nookies from 'nookies';
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Header from '../../components/header'
import Script from 'next/script'
// import Course from '../components/upcoming'
// import {getMeData} from '../components/upcoming'
// import Boxes from '../components/boxes'
import Footer from '../../components/footer'
import LoginComponent from '../../components/loginComponent';
import { useRouter } from 'next/router';
import Link from 'next/link';
import GetCoursesList from '../adminCourseList'


export default function AdminDashboard() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="admin-dashboard_main">
       <h1>Velkommen Admin</h1>
       <div className="create-new_btn">
        <Link href="/"><a>Legg til nytt kurs</a></Link>
       </div>
       

     
      
       
      </main>
      
      
 
    </div>
  )
}