import id from '../../pages/details/[id]'
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";


export default function AllCourses() {
  const router = useRouter();
  const [courses, setCourses] = useState([]);

  const handleOnClick = (id) => {
    router.push(`/${id}`);
  };

  useEffect(() => {
    const getCourses = async () => {
      const response = await fetch("http://localhost:1337/api/courses");
      const data = await response.json();
      const results = data.data;
      setCourses(results.data);
    };

    getCourses();
  }, []);

  console.log("courses", courses);

  return (
    <div className={styles.container}>
      <Head>
        <title>Dynamic routes example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
       
      </div>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to next.js</h1>

        <p className={styles.description}>
          We want to have multiple people pages
        </p>

        <div>
          <ul>
            {courses.map((course) => (
              <li key={course.id} onClick={() => handleOnClick(course.id)}>
                {course.kurs_id}
              </li>
            ))}
          </ul>
        </div>
      </main>

     
    </div>
  );
}