import nookies from 'nookies';
import Head from 'next/head'
// import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Header from '../../components/header'
import Script from 'next/script'
// import Course from '../components/upcoming'
// import {getMeData} from '../components/upcoming'
// import Boxes from '../components/boxes'
import Footer from '../../components/footer'
import LoginComponent from '../../components/loginComponent';
import { useRouter } from 'next/router';


export function LoginPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      
      <main className={styles.main}>
       
      
      <LoginComponent></LoginComponent>
     
      
       
      </main>
      
      <Footer></Footer>
     
      <div className="container">
<Script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></Script>
<Script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></Script>
<Script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></Script>
      </div>
    </div>
  )
}


export const getServerSideProps = async (ctx) => {
    const cookies = nookies.get(ctx)
    let user = null;
  
    if (cookies?.jwt) {
      try {
        const { data } = await 
  axios.get('http://localhost:1337/users/me', {
          headers: {
            Authorization:
              `Bearer ${cookies.jwt}`,
            },
        });
        user = data;
      } catch (e) {
        console.log(e);
      }
    }
  
    if (user) {
      return {
        redirect: {
          permanent: false,
          destination: '/INSER DESTINATION'
        }
      }
    }
  
    return {
      props: {}
    }
  }
  
  export default LoginPage;

  