import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image';
import Logo from '../../imgs/logo.png';


export default function Footer() {
  
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        
        </Head>
            <footer>
                <ul className="footer_links">
                <li className="footer_link"><a href="#">Spiseforstyrrelser</a></li>
                <li className="footer_link"><a href="#">Selvskading</a></li>
                <li className="footer_link"><a href="#">Behandling</a></li>
                <li className="footer_link"><a href="#">Hvordan søke</a></li>
                <li className="footer_link"><a href="#">Priser</a></li>
                </ul>
            
<ul className="list-group list-group-horizontal-sm">
<form className="row g-3">
  <div className="col-auto">
      <h4>Abonner på nyhetsbrev</h4>
    <label htmlFor="exampleFormControlInput1" className="form-label">E-post:</label>
    <input type="email" className="form-control" id="exampleFormControlInput1" ></input>
    <button type="submit" className="btn btn-primary mb-3">Abonner</button>
  </div>
 
  
    
  
</form>

</ul>
<ul className="footer_info">
  <li className="footer-sult">Villa SULT - Institutt for <br></br> spiseforstyrrelser </li>
  
  <li className="footer_adress">
  Kruses gate 8, 0263 Oslo 
  <br></br> 
  Org.nr. 913 110 836 
  <br></br>
  post@villasult.no
  </li>
  <li className="footer_some">Følg oss på 
  <a href="#"> Facebook</a>,
  <br></br>
  <a href="#"> Instagram</a> og
  <a href="#"> YouTube</a>
  </li>
</ul>


</footer>
<p className="copyright">© 2022 Villa Sult – Institutt for spiseforstyrrelser.</p>

     </div>
    );
  }