
import { filteringAnArray } from "../search/filterArray";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";

import Header from "../../components/header";
import Footer from '../../components/footer';

export default function CoursesList() {
const router = useRouter();
  const [courses, setCourses] = useState([]);

  const handleOnClick = (id) => {
    router.push(`/details/${id}`);
  };

  useEffect(() => {
    const getCourses = async () => {
        const response = await fetch('http://localhost:1337/api/courses/');
        const data = await response.json();
        const result = data.data;
       console.log(result);
        setCourses(result);
      
    };

    getCourses();
  }, []);

  console.log("courses", courses);

  async function getAllCourses() {
    const response = await fetch('http://localhost:1337/api/courses/');
    const data = await response.json();
    const result = data.data;

console.log(result)

const searchInput = document.querySelector("#searchBar")


// function courseCards(array){
//         for (let i = 0; i < array.length; i++) {
//             document.querySelector('.all-courses').innerHTML += `
//             <div>
//             <ul>
//               ${courses.map((course) => (
//                   <div className="all-courses_card"> 
//                   <div className="short-title_box"><h3>{course.attributes.short_title}</h3></div>
//                   <div className="date_box"><h4>{course.attributes.kurs_date}</h4></div>
//                 <li key={course.id} onClick={() => handleOnClick(course.id)}>
//                 <div className="details_btn">
//           <a>Les mer/Påmelding</a>
//           </div>
//                 </li>
//                 </div>
//               ))}
//             </ul>
//           </div>
//                 `;
//     };
   
// }
// courseCards(result)

searchInput.onkeyup = (()=>{
    document.querySelector(".all-courses").innerHTML = ""
    let searchArray = filteringAnArray(result, searchInput.value)
    getCourses(searchArray)
})
 }

   

 getAllCourses();

  return (
    <div className={styles.container}>
      <Head>
        <title>Dynamic routes example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      </div>
    
      <main className="main">
      <form className="d-flex">
            <input className="form-control me-2" id="searchBar" type="search" placeholder="Search" aria-label="Search"></input>
            <button className="btn btn-outline-success" type="submit">Search</button>
          </form>
        {/* <div className="all-courses" id="coursesList"></div>
       */}
        <div className="all-courses" id="coursesList">
          <ul>
            {courses.map((course) => (
                <div className="all-courses_card"> 
                <div className="short-title_box"><h3>{course.attributes.short_title}</h3></div>
                <div className="date_box"><h4>{course.attributes.kurs_date}</h4></div>
              <li key={course.id} onClick={() => handleOnClick(course.id)}>
              <div className="details_btn">
        <a>Les mer/Påmelding</a>
        </div>
              </li>
              </div>
            ))}
          </ul>
        </div>
      </main>
      </div>
    );


}