import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import AdminHeader from '../../components/header/adminHeader'
import Script from 'next/script'
// import Course from '../components/upcoming'
// import {getMeData} from '../components/upcoming'
// import Boxes from '../components/boxes'
import Footer from '../../components/footer'
import Link from 'next/link'
import AdminDashboard from '../../components/adminDashbord'
import AllCoursesList from '../../components/adminCourseList'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AdminHeader></AdminHeader>
      
      <main className="admin-main">
    <AdminDashboard></AdminDashboard>
    <div className="admin-courses_list"></div>
      </main>
      
      <Footer></Footer>
     
      <div className="container">
<Script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></Script>
<Script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></Script>
<Script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></Script>
      </div>
    </div>
  )
}
